# Generated by Django 5.0.4 on 2024-04-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chargingstation_brand_chargingstation_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargingstation',
            old_name='available_slots',
            new_name='available_chargers',
        ),
    ]
